### ISSUE TITLE
The language does not exist

### ISSUE THREAD

**Issue by benju69** [FutureMind/bitrise-step-huawei-app-gallery-apk-distribution#1]
Hi I have this error in my log: 
Updating App File Information - add previoulsy uploaded file
FileName: build_936.apk
Updating App File Information - Done
Message:[AppGalleryConnectPublishService]The language does not exist !
Code: 204144650

**Comment by pawelcala** [comment]
Hi, can you please tell me what did you enter in `lang` field? 
Here is list of supported languages [supported languages](https://developer.huawei.com/consumer/en/service/hms/catalog/AGCConnectAPI.html?page=hmssdk_appGalleryConnect_api_reference_language_type)

**Comment by benju69** [comment]
In the lang field I have en-EN, ok now I see why :)
