### ISSUE TITLE
Update link : 'For more languages refer to Language Types'

### ISSUE THREAD

**Issue by lmr001** [FutureMind/bitrise-step-huawei-app-gallery-apk-distribution#2]
https://developer.huawei.com/consumer/en/doc/development/AppGallery-connect-Guides/agcapi-reference-langtype

**Comment by lmr001** [comment]
I'm getting the following failure:
Lang is: en-EN
Obtaining a Token
Obtaining a Token - Done
Obtaining the File Upload URL
Obtaining the File Upload URL - Done
Uploading a File
Uploading a File - Done
Updating App File Information - add previoulsy [REDACTED]ed file
FileName: build_102.apk
Updating App File Information - Done

**Message:[AppGalleryConnectPublishService]The language does not exist !
Code: 204144650**

**Comment by klamborowski** [comment]
@lmr001 You should use one of allowed languages from page you linked in first comment. 

For English only this two is available:
(![obraz](https://user-images.githubusercontent.com/4972310/83527060-960c2380-a4e7-11ea-9b99-775486e9e4dc.png))

**Comment by lmr001** [comment]
> @lmr001 You should use one of allowed languages from page you linked in first comment.
> 
> For English only this two is available:
> (![obraz](https://user-images.githubusercontent.com/4972310/83527060-960c2380-a4e7-11ea-9b99-775486e9e4dc.png))

@klamborowski  I did change it, see below. 

Lang is: **en-US**
Obtaining a Token
Obtaining a Token - Done
Obtaining the File Upload URL
Obtaining the File Upload URL - Done
Uploading a File
Uploading a File - Done
Updating App File Information - add previoulsy [REDACTED]ed file
FileName: build_104.apk
Updating App File Information - Done
Message:[AppGalleryConnectPublishService]The language does not exist !
Code: 204144650

**Comment by klamborowski** [comment]
I've made some test runs.
en-US -> Failed (The language does not exist ! Code: 204144650)
en-GB -> Failed (The language does not exist ! Code: 204144650)
pl-PL -> Success

Both en languages is valid according to Huawei documentation.
https://developer.huawei.com/consumer/en/doc/development/AppGallery-connect-References/agcapi-app-file-info_v2

@lmr001 Did you submit issue to Huawei bug tracker?

**Comment by lmr001** [comment]
@klamborowski No I did not submit issue.

**Comment by klamborowski** [comment]
@lmr001 I've got response from Huawei.

> Dear developer,
> 
> Please set en-US or en-GB language information first.
> 
> You can find instruction in https://developer.huawei.com/consumer/en/doc/development/AppGallery-connect-References/agcapi-app-language-info_update_v2.
> 
> Sincerely,
> 
> Huawei Developer Alliance Support Team

Probably it could also done via App Gallery Console. Could you check AppGallery Connect -> App information -> Localization and let me know which languages you have there?

For me there is only Polish, which could be reason of failures on en family language:
![obraz](https://user-images.githubusercontent.com/4972310/84257849-4d232300-ab16-11ea-94e9-537de099f492.png)

**Comment by lmr001** [comment]
![Screenshot 2020-06-11 at 08 31 11](https://user-images.githubusercontent.com/1047104/84352624-f83ae780-abbd-11ea-808b-c296bc1518f6.png)

**Comment by klamborowski** [comment]
@lmr001 for English (UK) you should use en-GB.

Please try it and let me know if it helps.

**Comment by klamborowski** [comment]
@lmr001 did you try solution above?

**Comment by lmr001** [comment]
@klamborowski The solution works. This can be closed.
